---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: plugins/docker
    settings:
      username:
        from_secret: DHU
      password:
        from_secret: DHP
      repo: ezkrg/bitlbee-libpurple
      tags: test
      when:
        branch:
        - master

  - name: release
    image: plugins/docker
    settings:
      username:
        from_secret: DHU
      password:
        from_secret: DHP
      repo: ezkrg/bitlbee-libpurple
      tags:
        - ${DRONE_TAG}
        - latest
      when:
        event:
        - tag
---
kind: signature
hmac: de7b4e1cbe04b744ed6cad903e7f00d145f9bdd1d34068ba1520a9f3071cb74f

...
