---
kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: docker:stable-dind
    privileged: true
    detach: true
    command: [ "dockerd", "--host=tcp://0.0.0.0:2375" ]

  - name: test
    image: docker:stable
    environment:
      USER:
        from_secret: DHU
      PASSWORD:
        from_secret: DHP
      DOCKER_BUILDKIT: 1
      DOCKER_HOST: tcp://docker:2375
    commands:
    - sleep 20
    - echo $PASSWORD | docker login --username $USER --password-stdin
    - docker build -t ezkrg/bitlbee-libpurple:test .
    - docker push ezkrg/bitlbee-libpurple:test

  - name: release
    image: docker:stable
    environment:
      USER:
        from_secret: DHU
      PASSWORD:
        from_secret: DHP
      DOCKER_BUILDKIT: 1
      DOCKER_HOST: tcp://docker:2375
    volumes:
    - name: docker-certs-client
      path: /root/.docker
    commands:
    - docker tag ezkrg/bitlbee-libpurple:test ezkrg/bitlbee-libpurple:$DRONE_TAG
    - docker push ezkrg/bitlbee-libpurple:$DRONE_TAG
    - docker tag ezkrg/bitlbee-libpurple:test ezkrg/bitlbee-libpurple:latest
    - docker push ezkrg/bitlbee-libpurple:latest
    when:
      event:
      - tag

---
kind: signature
hmac: 93c2096e49d600543a3177e2cf2d6b67096377d71f3727f72579da6d39510dec

...
